### ISSUE TITLE
Thank you very much for your excellent work! I have two questions:

### ISSUE THREAD

**Issue by Sungden** [himashi92/Co-BioNet#8]
Thank you very much for your excellent work! I have two questions:
(1). In the paper, where specifically does the term 'uncertainty' in the title manifest? Is it in step 6? I didn't see a step where uncertainty is calculated.
(2). How is Equation 1 derived?
Thank you.

**Comment by himashi92** [comment]
Thanks for your interest in our work!

1) We use two critics to generate confidence maps from each prediction. These confidence maps are then used during masked spatial loss calculation. From the confidence map, we create another mask showing high-confidence regions to train two segmentation models. With that, we guide two models, which are the certain and uncertain areas predicted by each model. Both step 5 & 6 are related to this calculation.

2) Equation 1 is about the Principle of consensus. That is, if the two models, f1 and f2, often disagree when making predictions on the same data point, it implies that at least one is making an error. This is because, if both models were accurate, they should agree most of the time. Therefore, reducing the probability of disagreement (making the left-hand side of Equation 1 smaller) will, in turn, reduce the maximum error rate of the individual models. However, in this paper, we don't have multiple views of the same data, instead of that, we showed using a devised optimization strategy, we can still create two segmentation models with distinct representation power.

Kind regards,
Himashi

**Comment by Sungden** [comment]
Thanks for your answer!
